### ISSUE TITLE
Create a new inner page " Trainer Profiles

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#15]
Hello Arish,

Create a inner page  on O2 Skills website by name Trainer Profiles and upload attached data in the page.

Ex: Our Team--- Trainers Profiles
[trainer profiles.docx](https://github.com/adnan1111/o2skills/files/195445/trainer.profiles.docx)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Prasad,

Please kindly provide images separately by adding attachment here. Please make profile image title as name of the profile.

**Comment by arish-ddeveloper** [comment]
Link to the page: http://o2skills.com/our-team/trainer-profiles/
