### ISSUE TITLE
Images for Trainer Profiles of O2 Skills

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#16]
Hello Arish,

Attached are the images of the trainers of O2 Skills . The content is sent in earlier mail

![aleena spa trainer](https://cloud.githubusercontent.com/assets/16165106/14226583/d04c0702-f903-11e5-8230-c6d528808836.jpg)

Ms. LAIRISUKJANG DKHAR SAWIAN (Aleena)  is SPA Therapist from Meghalaya with 10 Years of experience and her hobbies are playing chess.
![asiya begum beauty trainer](https://cloud.githubusercontent.com/assets/16165106/14226585/d07b2370-f903-11e5-9b1f-58da4cf21256.jpg)
Ms. Asiya Begum is a Beauty trainer with  5 years of experience as beautician.
![bikash hospitality trainer](https://cloud.githubusercontent.com/assets/16165106/14226584/d0763e28-f903-11e5-9f83-a1f9ec4382a3.jpg)
Mr. Bikash Krushna Das is a Hospitality trainer with 8 years of experience and joined O2 from Sarada College of Hotel Management.
![i deepak](https://cloud.githubusercontent.com/assets/16165106/14226586/d082e54c-f903-11e5-8a44-669f714a5a91.jpg)
Mr. Deepak Kumar is Hospitality Trainer with 18 Years of experience from reputed Hotel Management college before joining with O2
![jyothi beauty trainer](https://cloud.githubusercontent.com/assets/16165106/14226588/d085b218-f903-11e5-9ce8-bf7fb7f40e50.jpg)
Ms. Gorre Jyothi is a Beauty trainer with  9 years of experience as beautician.
![niharika beauty trainer](https://cloud.githubusercontent.com/assets/16165106/14226587/d0851b64-f903-11e5-85aa-af259b9cc86e.jpg)
Ms. Niharika is a Hair & Beauty trainer with 7 years of experience in various organisations like VLCC, Jawed Habib etc.
![penchaliah naidu](https://cloud.githubusercontent.com/assets/16165106/14226589/d088663e-f903-11e5-9254-044bf5fd4b68.jpg)
Mr.Penchalaih Naidu is IT & Soft Skills trainer with 5 years of experience and joined O2 skills from Tech Mahindra.
![premi spa trainer](https://cloud.githubusercontent.com/assets/16165106/14226590/d0a1096e-f903-11e5-8fc8-881b0c4ce7ed.jpg)
Ms. Premi is a SPA trainer with 7 years of experience in O2 spa outlets Pan India.
![ramesh it trainer](https://cloud.githubusercontent.com/assets/16165106/14226591/d0aabd2e-f903-11e5-975c-77f527cdd688.jpg)
Mr. Ramesh is IT trainer with 10 years of teaching experience in different graduation colleges.
![shantha kumari beauty trainer](https://cloud.githubusercontent.com/assets/16165106/14226592/d0b5e8ca-f903-11e5-9e15-d2055d7c4bf4.jpg)
Ms. Shantha Kumari is a Hair & beauty trainer with 10 years of experience and hobbies are reading books.
![srikanth hospitality trainer](https://cloud.githubusercontent.com/assets/16165106/14226594/d0b9fb04-f903-11e5-8d2a-9f2a4f7ab878.jpg)
Mr. Srikanth is Hospitality Trainer with 3+ Years of experience from Hotel management industry and joined O2.
![vijay hospitality trainer](https://cloud.githubusercontent.com/assets/16165106/14226593/d0b95848-f903-11e5-9ed5-636f776f1e37.jpg)
Mr. Vijay Kotna is a Hospitality trainer with 14 years of rich experience and joined O2 from Sarada College of Hotel Management

**Comment by arish-ddeveloper** [comment]
Done.
