### ISSUE TITLE
Application form in  O2 Skills Inner Pages

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#17]
Hello Arish,

For Below pages at the end of the content create a button by name " Click Here to Apply"  and  the customer has to redirected to "http://o2skills.com/application-form/"

http://o2skills.com/courses/beauty-and-hair-dressing/

http://o2skills.com/courses/spa-and-wellness-industry/

http://o2skills.com/courses/craftsman-in-housekeeping/

http://o2skills.com/courses/craftsman-in-food-and-beverages/

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done.
