### ISSUE TITLE
Enable Enquiry Forms

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#2]
Hello Arish,

Keep a page with name Flyer. When we click on the page it should redirect to flyer image below flyer image keep enquiry button. Enable the attached enquiry form. The data filled in the enquiry form should go to contact@o2skills.com
[Enquiry form (3).docx](https://github.com/adnan1111/o2skills/files/180683/Enquiry.form.3.docx)
![flyer 19 draft final 1](https://cloud.githubusercontent.com/assets/16165106/13897282/73e5a3ce-edd2-11e5-9530-ffabc03c2d64.jpg)

**Comment by arish-ddeveloper** [comment]
Done.
