### ISSUE TITLE
Decrease the sliders sizes

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#3]
Hello Arish

Decrease the slider slizes on o2skills.com website.

**Comment by arish-ddeveloper** [comment]
Hi Prasad,

Please resize the following images 

http://o2skills.com/wp-content/uploads/2014/08/Housekeeping.jpg
http://o2skills.com/wp-content/uploads/2014/08/Food-Baverage.jpg
http://o2skills.com/wp-content/uploads/2014/08/Beauty.jpg
http://o2skills.com/wp-content/uploads/2014/08/SPA-Wellness-Management.jpg

New size: 1000x270

**Comment by arish-ddeveloper** [comment]
Done.
