### ISSUE TITLE
Add hyperlink with "100% Guarantee Courses" on Home Page

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#4]
Hello Arish,

Create a hyper link with text 100% Guarantee Courses on Home Page above the Placement Partners. The hyperlink should redirected to flyer image and create a button Enquiry Form under the image. Attached is the flyer image and enquiry form

![flyer 19 draft final 1](https://cloud.githubusercontent.com/assets/16165106/13897366/853f53ba-edd5-11e5-99d0-85c8be8e0a38.jpg)
[Enquiry form (3).docx](https://github.com/adnan1111/o2skills/files/180706/Enquiry.form.3.docx)

Regards
Prasad
[Application Form SWM BH HM courses (1).docx](https://github.com/adnan1111/o2skills/files/180701/Application.Form.SWM.BH.HM.courses.1.docx)

**Comment by arish-ddeveloper** [comment]
Done.
