### ISSUE TITLE
Remove the content in programs page

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2skills#5]
Hello Arish

Remove content in below url

http://o2skills.com/courses/

Remove Retail box
Remove Information and Communication technology box
Remove Fashion Designing box
Remove Security box
Remove Health Care box
In Hospitality Remove Front Desk, waiter  and add Food and Beverage and House Keeping.
In Spa and Wellness Remove Spa Therapist Remove Spa Traineer\

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done.
